### ISSUE TITLE
incorrect redirect for nix manual

### ISSUE THREAD

**Issue by raboof** [NixOS/nix.dev#1005]
https://nixos.org/manual/nix/unstable/language/builtins#builtins-fetchurl redirects to https://nix.dev/manual/nix/development/language/builtins which then redirects to https://hydra.nixos.org/build/263397466/download/1/manual/language/builtins

I think that should have ended up at https://hydra.nixos.org/build/263397466/download/1/manual/language/builtins.html , but I'm not sure which redirect is wrong :)

**Comment by fricklerhandwerk** [comment]
Yes, all of this is a mess because URL rewriting doesn't work as it's supposed to, neither on the nix.dev side (by Netlify) nor on Hydra (don't even know what that uses, maybe nginx?). All the information required for that is in place though.

What we could do to not have all those redirects constantly broken is
- point `nixos.org/manual/nix/unstable` to the latest Nix release instead of to the `master` build.

  It would change semantics, but wouldn't require spamming nix.dev commit history with automatic updates

- automatically update the reference to the latest `master` build at some interval

  this would preserve semantics, but would be ridiculously wasteful and produce a lot of noise in Git

- fix Hydra to do the right thing with the URLs

  I'd actually prefer that, but wouldn't exactly know where to start, and that would also require help from others, such as for re-deploying

**Comment by raboof** [comment]
> What we could do to to not have all those redirects constantly broken is
> 
>     * point `nixos.org/manual/nix/unstable` to the latest Nix release instead of to the `master` build.
>       It would change semantics

Right: the balance between having updates to the docs quickly available, vs potentially documenting things that aren't actually released yet. Does the nix team have a preference?

**Comment by fricklerhandwerk** [comment]
I took the shortcut by redirecting to the latest release.

Closed by https://github.com/NixOS/nixos-homepage/pull/1486
