### ISSUE TITLE
Make getting started more explicit please

### ISSUE THREAD

**Issue by mpstaton** [NixOS/nix.dev#1086]
Team,

The documentation is extensive.  But, I've been trying to set up Nix on my latest Mac (all things current as of November) all day today.

I installed it, and upon the SECOND instruction to nix-shell -p cosway lolcat I hit errors.  

<img width="866" alt="image" src="https://github.com/user-attachments/assets/5be6eaaf-79d0-4767-9a3a-5d1165745f6f">

I get that you can't control for MY environment, but even when I search the errors and read the forums I get no explanation.  

On another YouTube tutorial I tried nix-shell -p neofetch --run neofetch and that worked just fine.  Is it the cosway library?
<img width="782" alt="image" src="https://github.com/user-attachments/assets/13d91b49-afaf-4ed4-9d33-187e08588f3f">

Of course, at some point I just decided to install it again, but I have to "remove" all current nix directories, which, by the way are invisible on MacOS so I can't even find them. There seem to be nix references in etc and nix

<img width="688" alt="image" src="https://github.com/user-attachments/assets/cfe9a11c-0dcb-4880-8145-81ba052eaf83">

Seems to me you should have better instructions on uninstalling as well?  

Please just make getting started easier.  And, you should allow for people to flag specific parts of your Docs.  All I can do is come here and file a general complaint...  when things went wrong for me at a very specific spot.

**Comment by jfly** [comment]
Unfortunately, you've got a simple typo here: `nix-shell -p cosway`. It should be `cowsay`. Unfortunately, it results in a pretty intimidating error message.

This actually does give a much nicer error with flakes, but I think nix.dev intentionally avoids documenting flakes because they're unstable/experimental.

```
$ nix shell nixpkgs#cosway
error: flake 'flake:nixpkgs' does not provide attribute 'packages.x86_64-linux.cosway', 'legacyPackages.x86_64-linux.cosway' or 'cosway'
       Did you mean one of costa, cowsay or sway?
```

**Comment by mpstaton** [comment]
OMG, why is it always a typo and why don't error messages say "are you sure it's not a typo?"  

I spent another few hours trying from scratch on my Ubuntu machine, and after using the Determinate Systems installer -- amazing by the way, just recommend that please, especially after the uninstall hell I found. 

Anyway, I got to here (without realizing it was a typo) 

![Screenshot From 2024-11-24 00-21-05](https://github.com/user-attachments/assets/19b8d706-89aa-40ec-88d8-b94f7f45b76a)

As you can see, the same unhelpful error was thrown.  

Anyway, I came to saw your response and was immediately "cowsay" not "cosway" -- no idea why I never saw that, but super annoyed the error message didn't surface that possibility.  

I literally spent hours uninstalling Nix from my Mac and then cleaning up the Ubuntu machine just to even have a shot at Nix working.  

Thanks, consider the error messages ;)

**Comment by mpstaton** [comment]
Oh, and for fun, this is the sticking point I can't get past on my Mac now, and I have no idea if it means I won't be able to use Nix without wiping the entire computer and starting from scratch.  And of course I haven't backed up my Time Machine for like 11 months.  

<img width="572" alt="image" src="https://github.com/user-attachments/assets/05e80188-5774-442e-afa3-a1b3cb776f0a">

**Comment by mpstaton** [comment]
And just because I'm a whiner, the entire purpose of me setting up Nix was 

1. I want to jump between machines, 
2. I want the cost of clean wipes of any machine for any of my team to be near zero, 
3. I want to be sure when I send code to clients and when they send stuff back to me that there is no "3 days lost to setup and config hell".  

So, this means that some large number of humans on the planet live in a "Nix" world of bunnies and rainbows -- they can seamlessly jump from computer to computer, and they can have passerbys stop in on their code and get insta-started with no headaches.  

But not me, and not the dabbles, or the amateurs.  For us, we can live in that hell just trying to get Nix to work.   

Of course I could have just seen my own typo.  But also is copypasta into the command line the best way to propagate software?

Just remember: Affinity was supposed to eat Adobe for pure joy of the technical aspects of design.  But, Canva, which was just a slightly easier flier maker for years, was value at $6B and they bought Affinity.  So, helping more and more people get started is the way to win.  (That's me justifying my rant.)

**Comment by jfly** [comment]
> super annoyed the error message didn't surface that possibility

As I mentioned before: if you use flakes (a new, experimental, unstable feature of nix), you get a nice error message here.

Unfortunately, beginners don't (yet?) benefit from that work because it's not yet stable and therefore isn't documented. My attitude is that addressing the weird state that is flakes (either stabilizing it, or removing it) is one of the biggest things we can do to improve the beginner experience with nix. Unfortunately, it seems like we're a ways from figuring that out.

> Oh, and for fun, this is the sticking point I can't get past on my Mac now, and I have no idea if it means I won't be able to use Nix without wiping the entire computer and starting from scratch

I'd suggest filing a separate issue for just this.

> So, helping more and more people get started is the way to win.

I agree with you. Thank you for taking the time to file this issue.

I'm going to close this, feel free to file other issues for more specific things (such as the APFS issue you showed above). 

Sorry for the bumpy start! I promise if you get past the speedbumps, you'll find that nix/nixos can solve many of the problems that attracted you to it in the first place.
