### ISSUE TITLE
Links to pages do not work due to server returning index.html instead of assets

### ISSUE THREAD

**Issue by justinwoo** [NixOS/nix.dev#273]
Links like <https://nix.dev/en/latest/faq.html#how-do-i-fix-error-current-nix-store-schema-is-version-10-but-i-only-support-7> give you problems:

![image](https://user-images.githubusercontent.com/2396926/180732323-68210992-030d-449f-abae-edbb7340d12e.png)

**Comment by fricklerhandwerk** [comment]
Is it about the `/latest` part? Where do you find such links?

**Comment by justinwoo** [comment]
you find these links on nix discourse and other sources that are attempting to correctly deep link into nix.dev so that people can read content. note that this bug also makes bookmarks of nix.dev useless.

**Comment by JeremiahSecrist** [comment]
I've done testing and it seems that _any_ invalid link behaves in this manner. So I can glean that one part of this issue is 404.html is not functioning on top of improper links being made. As to improper links being made I need to see a recent even of this to track it down. Specifically a reproducible way to generate bad links off the site via interacting with it.

**Comment by amad3us47** [comment]
where i can find the /latest file in the github repo of this site ?

**Comment by amad3us47** [comment]
the bug is in /en/latest directory 
where is the file location in the github repo files?

**Comment by willbush** [comment]
Seems like this can be closed? I'm getting a proper 404 page.

**Comment by fricklerhandwerk** [comment]
The issue itself seems to be obsolete now, but that URL should not 404 but redirect to https://nix.dev/guides/troubleshooting#how-to-fix-error-current-nix-store-schema-is-version-10-but-i-only-support-7

We still need https://github.com/NixOS/nix.dev/issues/740
