### ISSUE TITLE
html formatting of shell output

### ISSUE THREAD

**Issue by olafklingt** [NixOS/nix.dev#339]
nix.dev seem to not distinguish between shell commands and console output which would be good.

```shell-session
ls
```

and

```console
filename.txt
```

or 

    filename.txt

**Comment by fricklerhandwerk** [comment]
It seems #320 was not successful. Will investigate.

**Comment by olafklingt** [comment]
When i read the pr correctly it doesnt aim to distinguish between shell-session and none

**Comment by fricklerhandwerk** [comment]
I had tested the PR and it worked. It's also not about the class, because the Nix language tutorial now uses `console` instead of `shell-session` - but fixing that doesn't change anything. I tried rebuilding with `make clean; make html; ./live`, and it still doesn't display correctly. @sbruder do you have an idea?

**Comment by willbush** [comment]
![20240717_03h06m14s_grim](https://github.com/user-attachments/assets/8134c47a-0945-411a-b422-ea76799b5977)
I looked at the nix language tutorial since it was mentioned. Seems issue has been fixed?

**Comment by fricklerhandwerk** [comment]
Yes, thanks!
