### ISSUE TITLE
Issue on page /tutorials/nix-language.html

### ISSUE THREAD

**Issue by Ten0** [NixOS/nix.dev#345]
Helloo!

Just heard about nix.dev today at NixCon, great resource, thanks a lot!

So I basically don't know anything about Nix (which is a nice test run for this doc I guess) and I started going through it.

I noticed that this page mentions `pkgs.lib` at https://nix.dev/tutorials/nix-language#pkgs-lib
before it is actually shown how `pkgs.lib` gets there: https://nix.dev/tutorials/nix-language#derivations
later in the page, which makes this first section a bit difficult to read.

I think it might be nice to add a "detailed explanation" section there that mentions that this is explained in section X below - or something else along those lines.

Thanks again!

**Comment by domenkozar** [comment]
cc @fricklerhandwerk

**Comment by fricklerhandwerk** [comment]
Hi @Ten0, thanks for the feedback. You're absolutely right, beginners taking the tutorials make for the best tests we can get.

Trying to understand what exact problem you had there. `pkgs.lib` are pure Nix language functions, they are not derivations. Since the concept of derivations is not relevant for that, I don't see a point of referring to them. Could you go back to that state of mind where you read the `pkgs.lib` section and try to identify what exactly confused you and what would have helped you avoid that confusion? Would it for instance help noting that those library functions are just for transforming pure values, while actually building things is done somewhere else?

**Comment by Ten0** [comment]
So as I was reading this page I learnt about, in order:
1. [Search paths](https://nix.dev/tutorials/nix-language#search-path), and specifically `<nixpkgs/lib>`.
2. [pkgs.lib](https://nix.dev/tutorials/nix-language#pkgs-lib) "The `nixpkgs` repository contains an attribute set called `lib`", these functions are usually accessed through `pkgs.lib`.
3. [How we get `<nixpkgs>` into `pkgs`](https://nix.dev/tutorials/nix-language#derivations): `let pkgs = import <nixpkgs> {}; in "${pkgs.nix}`

So as I read 2, I wonder: "I thought we were importing nixpkgs through `<nixpkgs>` at some point, and suddenly it becomes a ~builtin `pkgs`? Or is that imported somehow? Where/when? Hmm something to remember to check for..."

And only as I read 3 (and the "Worked examples section that comes right after"), I get this information that it's just a convention to import `<nixpkgs>` in `pkgs` at the beginning of the files.

What I'm trying to avoid here is the mental load of having that "magic" that nixpkgs will end up in `pkgs` somehow until I've read 3, kind of load that the tutorial otherwise very well avoids by not constructing concepts before the concepts they depend on are explained (congratz!).

Thanks,

**Comment by fricklerhandwerk** [comment]
@Ten0 thank you very much, that really clarifies a lot, and indeed reminds me of a hunch I had when writing that section, which went almost exactly as you described. I had been focusing on helping readers decipher expressions like `pkgs.lib.whatever` but swept under the rug that one has to figure out how to get to `pkgs` in the first place. And at that time the final structure was not yet settled, so I didn't bother too much with wondering if `import` is already known or not. I will fix this immediately.
