### ISSUE TITLE
Enumerate who to contact to ask for granting permissions

### ISSUE THREAD

**Issue by minijackson** [NixOS/nix.dev#365]
As discussed during the NixCon 2022 Hackathon

Related to PR #362

---

Preliminary results:

Currently these people are org owners: https://github.com/orgs/NixOS/people?query=role%3Aowner 

Team leads should also be admins for GitHub teams, and have merge permissions to all repositories relevant to that team.
Team members (i.e., the team itself) should have triage permissions on those repositories, and write access to the team's project board.

Related: https://github.com/NixOS/foundation/issues/33

**Comment by fricklerhandwerk** [comment]
There is a team who has permissions to grant permissions. Is it https://github.com/orgs/NixOS/teams/board-members? @thufschmitt do you remember how we managed this for the Nix team?

**Comment by thufschmitt** [comment]
> There is a team who has permissions to grant permissions. Is it https://github.com/orgs/NixOS/teams/board-members? @thufschmitt do you remember how we managed this for the Nix team?

You link to https://github.com/orgs/NixOS/people?query=role%3Aowner somewhere else, which I guess is the right list. For the Nix team, I guess _someone_ (Eelco?) had the right rights and just did it. 

I'm not sure what your problem is, but if it's that you want to change the members of the team, it would probably make sense to ask for the team lead to get `admin` access to it so that you can manage that yourself.
