### ISSUE TITLE
Reproducibility referencing top-level directory with ./.: Unclear if it's the use of builtin.path with name that is the fix

### ISSUE THREAD

**Issue by kjeremy** [NixOS/nix.dev#428]
In https://nix.dev/anti-patterns/language#reproducibility-referencing-top-level-directory-with we see:

If someone builds the project in a differently named folder, they will get a different hash of the src and everything that depends on it.

> 
> A better way is to use builtins.path:
> ```nix
>  { pkgs ? import <nixpkgs> {}
>  }:
> 
>  pkgs.stdenv.mkDerivation {
>    name = "foobar";
> 
>    src = builtins.path { path = ./.; name = "myproject"; };
> }
> ```

It is unclear if just using `builtins.path` is sufficient or if `name` is needed for the solution.

**Comment by fricklerhandwerk** [comment]
Very good catch. `name` is required for the solution to make sense. The reason is that wherever the resulting store path is used, its contribution to the hash value will propagate to everywhere this derivation is used. As in the problem statement, when the surrounding directory name changes, the resulting store path changes, and that in turn will change all dependant derivation contents, and thus their store path hashes. While this is still reproducible *semantically*, i.e. a resulting binary will do the exact same thing, you lose all caching for no good reason. And by reproducibility we *want* to mean that if you don't change the inputs, the outputs should also stay the same. This article assumes that renaming the surrounding directory should not be considered a change.

It would be great if you could make that explicit in your own words – I doubt my explanation is super helpful for understanding or perfectly correct.
