### ISSUE TITLE
How do we separate Nix problems from Linux problems?

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix.dev#487]
A large number of problems that are reported by new users conflate errors originating with Nix with errors originating from the underlying Linux component they are configuring. 

In many cases it's somewhat obvious that Nix is doing exactly what it was configured to do and it would be better to go look at the Arch wiki or something else to troubleshoot the underlying issue.

**Comment by hugosenari** [comment]
The same way I don't know how we grow nixpkgs, I don't know how Arch grow theirs wiki.

But I would be happier if we grow ours wiki/docs (while I'm not contributing that much for it)
- Integrated troubleshooting experience (instructions of others Linux, unlikely to work with Nix/NixOS, sometimes even for user misuse of software)
- I only installed Arch because I give up to read Arch wiki to fix Ubuntu. There is even a marketing, SEO growth here.
- Sounds like "That’s not our job" (as Nix/NixOS community)

**Comment by fricklerhandwerk** [comment]
> I don't know how Arch grow theirs wiki.

As far as I know, by a bunch of people curating it tirelessly.

So yes, this issue absolutely is a judgment-free formulation of "not our problem", by which I mean: we can't possibly handle all of that at the moment, so we may as well focus on what's specific to the code we maintain.

**Comment by willbush** [comment]
What criteria would be sufficient to close this issue?

**Comment by fricklerhandwerk** [comment]
It's not really actionable, closing.
