### ISSUE TITLE
Add a "donate" link

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nix.dev#577]
We should feature a prominent link to our [OpenCollective](https://opencollective.com/nixos/projects/documentation-project) somewhere on the website.

An option is to add it under "Contributing".

**Comment by fricklerhandwerk** [comment]
> An option is to add it under "Contributing".

Good idea. This is essentially also the outcome of the workshop discussion and [a study on open source development](https://press.stripe.com/working-in-public): maintainers are not just much more effective at making meaningful changes due to their contextual knowledge, but also the bottleneck to accepting contributions and making sure they fit in well. We should indeed highlight that this is, apart from the suggested tasks, the most effective way of contributing at the moment.

**Comment by zmitchell** [comment]
Discussed in documentation team meeting, put the link in the sidebar so it's noticed. OpenCollective may provide markup/embeds for this already.

**Comment by henrik-ch** [comment]
A donate link exists on https://github.com/NixOS/nix.dev/blob/master/source/acknowledgments/sponsors.md .

**Comment by proofconstruction** [comment]
#702 adds a link to the autogenerated text output by the This Month in Nix Docs script.

**Comment by fricklerhandwerk** [comment]
We already have those for a long time, but I now added a highlight to make it more prominent: #703
